// <auto-generated />
namespace Olimpiad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewWay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewWay));
        
        string IMigrationMetadata.Id
        {
            get { return "202202160948091_New Way"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
